
# -v ~/venvs/bars/task_rest/media/data:/app/static/data

version: "3.9"  # optional since v1.27.0
services:
  task:
    image: task:0.1
    container_name: task
    network_mode: bridge
    #restart: always
    environment:
      DB_HOST: "192.168.1.31"
      DB_NAME: dbname
      DB_USER: postgres
      DB_PASSWORD: dbpass
    ports:
      - "8787:8787"
    volumes:
      - task-static:/opt/venv/app/static/data

volumes:
  task-static:
    external: true


