# source flask_conf.sh
export FLASK_ENV='development'
export FLASK_APP='run.py'
export DB_HOST='127.0.0.1'
export DB_NAME='zerodemo'
export DB_USER='zauther'
export DB_PASSWORD='borgen_boruh'
export DB_SCHEMA='webz'
export DB_AUTH='yes'
export JWT_TOKEN_SECRET='hxnEy4XoPQy4QKgJ3wvPhiHXmC6f5JZx'