CREATE TABLE public.talonz_clin_20
(
  tal_num serial PRIMARY KEY,
  crd_num character varying(20) REFERENCES cardz_clin (crd_num) NOT NULL,
  open_date date NOT NULL,
  close_date date NOT NULL,
  talon_type integer REFERENCES talonz_type (id) NOT NULL DEFAULT 1,
  
  talon_month smallint NOT NULL,
  mek smallint,
  
  polis_type integer REFERENCES public.polis_type (id),
  polis_num character varying(20),
  polis_ser character varying(20),
  smo integer,
  smo_okato character(5),
  ist_fin smallint,
  first_vflag smallint DEFAULT 1,
  finality smallint DEFAULT 1,
  doc_spec integer NOT NULL,
  doc_code integer NOT NULL,
  purp smallint,
  usl_ok smallint,
  for_pom smallint,
  rslt smallint,
  ishod smallint,
  visit_pol smallint NOT NULL DEFAULT 0,
  pol_days smallint,
  visit_home smallint NOT NULL DEFAULT 0,
  home_days smallint,
  visit_homstac smallint NOT NULL DEFAULT 0,
  visit_daystac smallint NOT NULL DEFAULT 0,
  days_at_homstac smallint,
  days_at_daystac smallint,
  npr_mo integer,
  npr_spec smallint,
  naprlech character varying(10),
  npr_date date,
  hosp_mo integer,
  nsndhosp character varying(10),
  extr smallint,
  prof_k smallint,
  ksk double precision,
  ksg character varying(10),
  sh character varying(5),
  ds0 character varying(8),
  ds1 character varying(8) REFERENCES public.mkb10(code) NOT NULL,
  ds2 character varying(8) REFERENCES public.mkb10(code),
  ds3 character varying(8),
  char1 smallint,
  char2 smallint,
  code_mes1 character varying(20),
  code_mes2 character varying(20),
  travma_type smallint,
  patient_age smallint,
  d_type character varying(3),
  created timestamp without time zone NOT NULL DEFAULT now(),
  modified timestamp without time zone NOT NULL DEFAULT now(),
  cuser integer REFERENCES public.users (id) NOT NULL DEFAULT 1
)